import json
import os
import openai
from pinecone import Pinecone
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Keys from env
openai_api_key = os.getenv("OPENAI_API_KEY")
pinecone_api_key = os.getenv("PINECONE_API_KEY")
pinecone_env = os.getenv("PINECONE_ENV")
# index_name = os.getenv("PINECONE_INDEX_NAME")
index_name = "my-index"

# Initialize OpenAI
openai_client = OpenAI(api_key=openai_api_key)

# Initialize Pinecone
pc = Pinecone(api_key=pinecone_api_key)
index = pc.Index(index_name)

# Optional: set model name (adjust depending on embedding model used)
EMBEDDING_MODEL = "text-embedding-3-small"
CHAT_MODEL = "gpt-4"

def get_embedding(text):
    """Create embedding vector for user query."""
    res = openai_client.embeddings.create(
        model=EMBEDDING_MODEL,
        input=text
    )
    return res.data[0].embedding

def query_vector_db(query, top_k=2):
    """Search Pinecone for top-k most relevant context chunks."""
    query_embedding = get_embedding(query)
    results = index.query(vector=query_embedding, top_k=top_k, include_metadata=True)
    for match in results["matches"]:
      print(match.metadata) 
    # import pdb; pdb.set_trace()  
    return [match["metadata"]["text"] for match in results["matches"]]

def build_final_prompt(user_input, context_chunk,extra_input):
    file_path1 = "/Users/akhilpendyala/Documents/Hackathon/Hackathon_2025/Instructions/instruct.txt"
    with open(file_path1, "r", encoding="utf-8") as f:
        text = f.read()
        text = text.replace('\n', '')

    """Create final prompt to send to GPT-4 with context + user request."""
    context_text = "\n\n".join(context_chunk)
    instruct = text
    
    return f"""You are an expert Python API automation engineer.
                Using the following context about the endpoint
                Use the instructions to structure the test cases according to our framework standards.
                If you need to include *any non-code text or explanations*, comment those lines with #

                Instructions :
                {instruct}

                Context:
                {context_text}

                Specific user Input:
                {user_input}

                Generate 10 test cases(5 positive, 2 negative and 3 edge case) in Python. 
                Generate a test file and a helper file,
                """
    
    
    # return '''You are an expert Python API automation engineer.
                # mention Test File: test_*_api.py, Helper File: *_api.py
    #         Your task:
    #         Generate high-quality Python test cases based on API context and instructions.

    #         Use the following structured input:

    #         ---------------------
    #         📘 Instructions:
    #         {instruct}

    #         🧠 Context about the API endpoint:
    #         {context_text}

    #         🎯 Specific User Request:
    #         {user_input}
    #         ---------------------

    #         🧪 Output Expectations:
    #         - Generate 10 test cases:
    #         • 5 Positive
    #         • 2 Negative
    #         • 3 Edge Cases
    #         - Produce two Python files:
    #         1. A test file containing the test cases
    #         2. A helper file with any setup/helper methods needed

    #         💬 Notes:
    #         - If you include any non-code explanations, **comment them out using `#`**
    #         - Follow best practices and our framework structure
    #         - **Add this header comment at the top of each file**:
    #         `# Generated by AutoTestGen ⚙️ — Powered by Team RRR 🚀`

    #         ✅ Return only the code for both `.py` files, clearly separated and add a heading above them Test File: test_*_api.py, Helper File: *_api.py'''

def generate_test_code(user_input,extra_input=""):
    """Orchestrates the entire flow from query to final response."""
    context_chunk = query_vector_db(user_input)
    final_prompt = build_final_prompt(user_input, context_chunk,extra_input)

    print("⏳ Sending to OpenAI...")
    response = openai_client.chat.completions.create(
        model=CHAT_MODEL,
        messages=[
            {"role": "system", "content": "You are a helpful attentive expert SDET assistant who writes automated test cases."},
            {"role": "user", "content": final_prompt}
        ],
        temperature=0.3
    )
    print("\n Generated Test Cases:\n")
    response = response.choices[0].message.content
    print(response)
    
    # output_dir = "GeneratedTests"
    # os.makedirs(output_dir, exist_ok=True)  # creates folder if not present
    # output_file = os.path.join(output_dir, "generated_output.py")
    # with open(output_file, "w", encoding="utf-8") as f:
    #       f.write(response.choices[0].message.content)
    
    return response

# Example usage
if __name__ == "__main__":
    # user_question = input("/csap/v1/allowed_indicators/")
    user_question = input("Enter your end point : ")
    # test_file_name = input("Enter the test file name : ")
    extra_input = input("Enter any specific input (Optional) : ")

    generate_test_code(user_question,extra_input)
